// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx prisma/seed.ts`,

  },
  // Programmatic datasource URL for Prisma CLI (Migrate).
  // Prefer DIRECT_URL (non-pooled 5432) to avoid PgBouncer DDL issues,
  // fall back to DATABASE_URL if DIRECT_URL is not set.
  datasource: {
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
